#27 - faq page
blumilksoftware/keating pull request #134
Opened 2024-08-22 08:03 UTC by kamilpiech97

Should close #27.

Preview:

[Screencast from 22-08-24 09:50:35.webm](https://github.com/user-attachments/assets/823eafe3-c18b-4725-ad91-11c34d999520)

2024-08-22 09:23 UTC, EwelinaSkrzypacz reviewed
I'm not sure if we need this +/- icon to reveal/hide answers. Also the answer is not on full width

![image](https://github.com/user-attachments/assets/a5a71e7f-2c22-4e56-8383-77791330ed7a)

2024-08-22 09:23 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Public/Faq.vue
> +              Pytania i odpowiedzi na najczęściej zadawane pytania
```suggestion
              Często zadawane pytania i odpowiedzi na nie
```

2024-08-22 09:32 UTC, krzysztofrewak commented
I would like to remove this collapsing feature. It's not necessary, I think.

2024-08-23 12:20 UTC, kamilpiech97 commented
> I would like to remove this collapsing feature. It's not necessary, I think.

Removed

2024-08-23 12:41 UTC, kamilpiech97 commented
> I'm not sure if we need this +/- icon to reveal/hide answers. Also the answer is not on full width
> 
> ![image](https://private-user-images.githubusercontent.com/56546832/360369364-a5a71e7f-2c22-4e56-8383-77791330ed7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTUwODQsIm5iZiI6MTcyNDQxNDc4NCwicGF0aCI6Ii81NjU0NjgzMi8zNjAzNjkzNjQtYTVhNzFlN2YtMmMyMi00ZTU2LTgzODMtNzc3OTEzMzBlZDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEyMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTc5ZDY2ZjliNDE4NDY2Zjk1MTY5Yjc2OTkxMWIyYjlkMDRjNDgxMTZkNjRjMzA4YzQ2N2NmOWI0NDhiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IabVt5f9ypW92YQAykoC-sHW0SuBuDf2GzlJJ6hupx0)

Updated. Image in description updated also :D

2024-08-23 12:46 UTC, EwelinaSkrzypacz submitted a review, later dismissed

2024-08-23 12:47 UTC, krzysztofrewak requested changes

2024-08-26 12:22 UTC, EwelinaSkrzypacz approved these changes

2024-09-07 11:40 UTC, krzysztofrewak approved these changes

2024-09-10 13:56 UTC, krzysztofrewak approved these changes

2024-09-10 13:57 UTC, merged